const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")

test("Control mantiene una sola experiencia sin selector Preparar/Culto", () => {
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  assert.doesNotMatch(control, /selah-modo-control|modoOperacion|cambiarModoOperacion/)
  assert.doesNotMatch(control, />\s*(?:🛠\s*)?Preparar\s*</)
  assert.doesNotMatch(control, />\s*●\s*Culto\s*</)
})

test("las ayudas contextuales son opcionales y se apagan por defecto en APK", () => {
  const ayudas = fs.readFileSync("components/ui/AyudaBotones.tsx", "utf8")
  const ajustes = fs.readFileSync("app/configuracion/page.tsx", "utf8")
  assert.match(ayudas, /selah-ayudas-contextuales/)
  assert.match(ayudas, /Capacitor[\s\S]{0,100}pointer: coarse/)
  assert.match(ayudas, /guardada === null \? !tactil/)
  assert.match(ajustes, /Ayudas sobre los botones/)
  assert.match(ajustes, /role="switch" aria-checked=\{ayudasContextuales\}/)
})

test("Control móvil agrupa acciones secundarias y muestra un solo estado prioritario", () => {
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  assert.match(control, /mostrarControlesExtraMobile/)
  assert.match(control, /Mostrar controles adicionales/)
  assert.match(control, /mostrarControlesExtraMobile \|\| autoAvanceActivo/)
  assert.match(control, /isMobile && socketConectado === true && proyectorConectado/)
  assert.match(control, /etiqueta="LISTO"/)
})

test("Control móvil usa un panel a la vez y oculta filtros avanzados", () => {
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  assert.match(control, /const alternarPanel = \(panel:/)
  assert.match(control, /if \(isMobile\) \{[\s\S]{0,220}setMostrarCultos\(false\)/)
  assert.match(control, /!isMobile \|\| mostrarFiltrosMobile/)
  assert.match(control, /⚙ Filtros/)
  assert.match(control, /!isMobile && <div[^>]*>[\s\S]{0,260}Proyectar ahora/)
})

test("Control móvil permite alternar rápidamente entre repertorio y lista", () => {
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  assert.equal((control.match(/id="panel-canciones"/g) || []).length, 1)
  assert.equal((control.match(/id="scroll-lista"/g) || []).length, 1)
  assert.match(control, /aria-label="Ir a la lista del culto"/)
  assert.match(control, /aria-label="Volver a buscar canciones"/)
  assert.match(control, /getElementById\("panel-canciones"\).*scrollIntoView/)
  assert.match(control, /getElementById\("scroll-lista"\).*scrollIntoView/)
})

test("el tour de Control móvil usa acciones reales de la APK", () => {
  const tours = fs.readFileSync("lib/tours.ts", "utf8")
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  const tourUi = fs.readFileSync("components/OnboardingTour.tsx", "utf8")
  const inicio = tours.indexOf("export const TOUR_CONTROL_MOBILE")
  const fin = tours.indexOf("// Genera los pasos según plataforma")
  const mobile = tours.slice(inicio, fin)
  assert.ok(inicio >= 0 && fin > inicio)
  assert.doesNotMatch(mobile, /Electron|Abrir el Proyector|segundo monitor/)
  assert.match(mobile, /Ir a la lista del culto/)
  assert.match(mobile, /scroll-lista/)
  assert.match(control, /tour-control-mobile-v2/)
  assert.match(control, /data-tour="controles-extra-mobile"/)
  assert.match(tourUi, /calc\(100vw - 24px\)/)
})

test("la lista mantiene visibles los controles de orden y resalta el elemento movido", () => {
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  assert.match(control, /indiceItemReordenando/)
  assert.match(control, /↕ REORDENANDO/)
  assert.match(control, /aria-label=\{`Subir /)
  assert.match(control, /aria-label=\{`Bajar /)
  assert.match(control, /setIndiceItemReordenando\(i - 1\)/)
  assert.match(control, /setIndiceItemReordenando\(i \+ 1\)/)
})

test("Dashboard y Control presentan un único flujo y una Galería principal", () => {
  const dashboard = fs.readFileSync("app/page.tsx", "utf8")
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  assert.doesNotMatch(dashboard, /selah-modo-control|Preparar próximo culto|Operar el culto/)
  assert.match(dashboard, /Control de Culto/)
  assert.match(control, /id="panel-galeria"/)
  assert.match(control, /mostrarGaleriaPanel/)
  assert.match(control, /procesarArchivoGaleria/)
  assert.match(control, /Galería móvil:[\s\S]{0,180}Registro de errores/)
})
