const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")

test("Control mantiene una sola experiencia sin selector Preparar/Culto", () => {
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  assert.doesNotMatch(control, /selah-modo-control|modoOperacion|cambiarModoOperacion/)
  assert.doesNotMatch(control, />\s*(?:🛠\s*)?Preparar\s*</)
  assert.doesNotMatch(control, />\s*●\s*Culto\s*</)
})

test("las ayudas contextuales son opcionales y se apagan por defecto en APK", () => {
  const ayudas = fs.readFileSync("components/ui/AyudaBotones.tsx", "utf8")
  const ajustes = fs.readFileSync("app/configuracion/page.tsx", "utf8")
  assert.match(ayudas, /selah-ayudas-contextuales/)
  assert.match(ayudas, /Capacitor[\s\S]{0,100}pointer: coarse/)
  assert.match(ayudas, /guardada === null \? !tactil/)
  assert.match(ajustes, /Ayudas sobre los botones/)
  assert.match(ajustes, /role="switch" aria-checked=\{ayudasContextuales\}/)
})

test("Control móvil agrupa acciones secundarias y muestra un solo estado prioritario", () => {
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  assert.match(control, /mostrarControlesExtraMobile/)
  assert.match(control, /Mostrar controles adicionales/)
  assert.match(control, /mostrarControlesExtraMobile \|\| autoAvanceActivo/)
  assert.match(control, /isMobile && socketConectado === true && proyectorConectado/)
  assert.match(control, /etiqueta="LISTO"/)
})

test("Control móvil usa un panel a la vez y oculta filtros avanzados", () => {
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  assert.match(control, /const alternarPanel = \(panel:/)
  assert.match(control, /if \(isMobile\) \{[\s\S]{0,220}setMostrarCultos\(false\)/)
  assert.match(control, /!isMobile \|\| mostrarFiltrosMobile/)
  assert.match(control, /⚙ Filtros/)
  assert.match(control, /!isMobile && <div[^>]*>[\s\S]{0,260}Proyectar ahora/)
})

test("Control móvil permite alternar rápidamente entre repertorio y lista", () => {
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  assert.equal((control.match(/id="panel-canciones"/g) || []).length, 1)
  assert.equal((control.match(/id="scroll-lista"/g) || []).length, 1)
  assert.match(control, /aria-label="Ir a la lista del culto"/)
  assert.match(control, /aria-label="Volver a buscar canciones"/)
  assert.match(control, /getElementById\("panel-canciones"\).*scrollIntoView/)
  assert.match(control, /getElementById\("scroll-lista"\).*scrollIntoView/)
})

test("el tour de Control móvil usa acciones reales de la APK", () => {
  const tours = fs.readFileSync("lib/tours.ts", "utf8")
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  const tourUi = fs.readFileSync("components/OnboardingTour.tsx", "utf8")
  const inicio = tours.indexOf("export const TOUR_CONTROL_MOBILE")
  const fin = tours.indexOf("// Genera los pasos según plataforma")
  const mobile = tours.slice(inicio, fin)
  assert.ok(inicio >= 0 && fin > inicio)
  assert.doesNotMatch(mobile, /Electron|Abrir el Proyector|segundo monitor/)
  assert.match(mobile, /Ir a la lista del culto/)
  assert.match(mobile, /scroll-lista/)
  assert.match(control, /tour-control-mobile-v2/)
  assert.match(control, /data-tour="controles-extra-mobile"/)
  assert.match(tourUi, /calc\(100vw - 24px\)/)
})

test("Transmisión tiene un recorrido seguro y repetible", () => {
  const tours = fs.readFileSync("lib/tours.ts", "utf8")
  const enVivo = fs.readFileSync("app/en-vivo/page.tsx", "utf8")
  const ajustes = fs.readFileSync("app/configuracion/page.tsx", "utf8")
  assert.match(tours, /export const TOUR_TRANSMISION/)
  assert.match(enVivo, /OnboardingTour id="tour-transmision-v1"/)
  assert.match(enVivo, /data-tour="tx-salida"/)
  assert.match(enVivo, /dataTour="tx-camaras"/)
  assert.match(enVivo, /dataTour="tx-salir-vivo"/)
  assert.match(enVivo, /dataTour="tx-emision-directa"/)
  assert.match(ajustes, /Tour de Transmisión/)
  assert.doesNotMatch(tours.slice(tours.indexOf("export const TOUR_TRANSMISION")), /\.click\(\)/)
})

test("Músicos explica su flujo sin activar audio durante el tour", () => {
  const tours = fs.readFileSync("lib/tours.ts", "utf8")
  const musicos = fs.readFileSync("app/musicos/page.tsx", "utf8")
  const ajustes = fs.readFileSync("app/configuracion/page.tsx", "utf8")
  const inicio = tours.indexOf("export const TOUR_MUSICOS")
  assert.ok(inicio >= 0)
  const tour = tours.slice(inicio)
  assert.match(musicos, /OnboardingTour id="tour-musicos-v1"/)
  assert.match(musicos, /data-tour="musicos-herramientas"/)
  assert.match(musicos, /data-tour="musicos-repertorio"/)
  assert.match(musicos, /data-tour="musicos-controles"/)
  assert.match(ajustes, /Tour de Músicos/)
  assert.doesNotMatch(tour, /getUserMedia|\.click\(\)/)
})

test("la Cámara móvil guía la vinculación sin ejecutar acciones", () => {
  const tours = fs.readFileSync("lib/tours.ts", "utf8")
  const camara = fs.readFileSync("app/camara/page.tsx", "utf8")
  const ajustes = fs.readFileSync("app/configuracion/page.tsx", "utf8")
  const inicio = tours.indexOf("export const TOUR_CAMARA_MOVIL")
  assert.ok(inicio >= 0)
  const tour = tours.slice(inicio)
  assert.match(camara, /OnboardingTour id="tour-camara-movil-v1"/)
  assert.match(camara, /data-tour="camara-codigo"/)
  assert.match(camara, /data-tour="camara-voltear"/)
  assert.match(camara, /data-tour="camara-estado"/)
  assert.match(ajustes, /isCapacitor \? \[\{ id: "tour-camara-movil-v1"/)
  assert.doesNotMatch(tour, /getUserMedia|\.click\(\)/)
})

test("Configuración tiene tour repetible sin recargar la APK", () => {
  const tours = fs.readFileSync("lib/tours.ts", "utf8")
  const ajustes = fs.readFileSync("app/configuracion/page.tsx", "utf8")
  const tourUi = fs.readFileSync("components/OnboardingTour.tsx", "utf8")
  assert.match(tours, /export const TOUR_CONFIGURACION/)
  assert.match(ajustes, /OnboardingTour id="tour-configuracion-v1"/)
  assert.match(ajustes, /data-tour="config-indice"/)
  assert.match(ajustes, /detail: \{ id: tourId \}/)
  assert.match(tourUi, /selah-iniciar-tour/)
  assert.match(tourUi, /setPaso\(0\)/)
})

test("Inicio orienta al usuario y Control incluye la Galería en sus tours", () => {
  const tours = fs.readFileSync("lib/tours.ts", "utf8")
  const inicio = fs.readFileSync("app/page.tsx", "utf8")
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  const ajustes = fs.readFileSync("app/configuracion/page.tsx", "utf8")
  assert.match(tours, /export const TOUR_INICIO/)
  assert.match(inicio, /OnboardingTour id="tour-inicio-v1"/)
  assert.match(inicio, /data-tour="inicio-control"/)
  assert.match(inicio, /data-tour="inicio-modulos"/)
  assert.match(control, /data-tour="galeria-toggle"/)
  assert.match(control, /aria-expanded=\{mostrarGaleriaPanel\}/)
  assert.ok((tours.match(/selector: "#panel-galeria"/g) || []).length >= 2)
  assert.match(ajustes, /Tour de Inicio/)
})

test("la vista previa flotante puede subir sin recortarse y respeta la ventana", () => {
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  assert.match(control, /createPortal\(/)
  assert.match(control, /document\.body/)
  assert.match(control, /limiteSuperiorPreview = \(\) => 56/)
  assert.match(control, /previewPanelRef\.current\?\.offsetHeight/)
  assert.match(control, /const p = limitarPosPreview\(actual\)/)
  assert.match(control, /window\.addEventListener\("resize", corregir\)/)
  assert.doesNotMatch(control, /PREVIEW_TOPE_Y/)
})

test("el divisor de Electron ajusta y recuerda el espacio entre biblioteca y lista", () => {
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  assert.match(control, /isElectronCtx \? `minmax\(0, \$\{anchoBiblioteca\}fr\) 12px/)
  assert.match(control, /role="separator"/)
  assert.match(control, /selah-control-ancho-biblioteca/)
  assert.match(control, /ArrowLeft/)
  assert.match(control, /ArrowRight/)
})

test("Historial explica estadísticas, filtros y registros", () => {
  const tours = fs.readFileSync("lib/tours.ts", "utf8")
  const historial = fs.readFileSync("app/historial/page.tsx", "utf8")
  const ajustes = fs.readFileSync("app/configuracion/page.tsx", "utf8")
  assert.match(tours, /export const TOUR_HISTORIAL/)
  assert.match(historial, /OnboardingTour id="tour-historial-v1"/)
  assert.match(historial, /data-tour="historial-resumen"/)
  assert.match(historial, /data-tour="historial-filtros"/)
  assert.match(historial, /data-tour="historial-cultos"/)
  assert.match(ajustes, /Tour de Historial/)
})

test("la lista mantiene visibles los controles de orden y resalta el elemento movido", () => {
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  assert.match(control, /indiceItemReordenando/)
  assert.match(control, /↕ REORDENANDO/)
  assert.match(control, /aria-label=\{`Reordenar /)
  assert.match(control, /esReordenando \? <>/)
  assert.match(control, /Terminar de reordenar/)
  assert.match(control, /setIndiceItemReordenando\(i - 1\)/)
  assert.match(control, /setIndiceItemReordenando\(i \+ 1\)/)
})

test("Dashboard y Control presentan un único flujo y una Galería principal", () => {
  const dashboard = fs.readFileSync("app/page.tsx", "utf8")
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  assert.doesNotMatch(dashboard, /selah-modo-control|Preparar próximo culto|Operar el culto/)
  assert.match(dashboard, /Control de Culto/)
  assert.match(control, /id="panel-galeria"/)
  assert.match(control, /mostrarGaleriaPanel/)
  assert.match(control, /procesarArchivoGaleria/)
  assert.match(control, /Galería móvil:[\s\S]{0,180}Registro de errores/)
  assert.match(control, /selah-galeria-cache-/)
  assert.match(control, /galeriaFiltrada\.map/)
  assert.match(control, /alternarGaleriaPrincipal/)
  assert.match(control, /eliminarMediaGaleria/)
  assert.match(control, /aria-label="Eliminar carpeta"/)
  assert.match(control, /Mover \$\{img\.nombre\} a una carpeta/)
})

test("Control conserva la lista por iglesia y recupera la presencia del proyector", () => {
  const control = fs.readFileSync("app/control/page.tsx", "utf8")
  const main = fs.readFileSync("electron/main.js", "utf8")
  assert.match(control, /selah-lista-culto-\$\{igId\}/)
  assert.match(control, /items:lista, listaId:listaIdActual, nombre:nombreCulto/)
  assert.match(control, /s\.on\("estado-presencia"/)
  assert.match(main, /const presenciaSala = \(sala\)/)
  assert.match(main, /controlEscritorioConectado:/)
  assert.match(main, /mainWindow\.webContents\.executeJavaScript/)
  assert.match(main, /http:\/\/localhost:3000\/proyectar/)
  assert.match(main, /socket\.emit\("estado-presencia", presenciaSala\(salaFinal\)\)/)
  assert.match(main, /setImmediate\(\(\) => emitirPresenciaSala\(sala\)\)/)
  assert.match(control, /puedeAbrirProyector: navigator\.userAgent\.includes\("Electron"\)/)
  assert.match(control, /buscarServidorEnRed/)
  assert.match(control, /setInterval\(\(\) => void sondearServidor\(\), 5000\)/)
  assert.match(control, /socketRef2\.current\?\.emit\("sincronizar-lista"/)
  assert.match(main, /socket\.on\("sincronizar-lista"/)
  assert.match(main, /revision:\+\+revisionListaSala/)
  assert.match(main, /io\.to\(sala\)\.emit\("lista-sincronizada"/)
  assert.doesNotMatch(control, /esCapacitor && !ip\)[\s\S]{0,100}return/)
})
